### PR TITLE
fix empty value for data that contains CDATA

### PR DESCRIPTION
**Pull request by chanpete**
ref: https://stackoverflow.com/questions/21548443/php-converting-xml-to-json-does-not-work-when-there-is-cdata

### CODE REVIEW

**Comment by haringsrob** [comment]
Hi @chanpete,

Do you have an example of a product sheet where this problem happens? Would be great to add a test case for this.

Regards,

**Comment by chanpete** [comment]
Hi @haringsrob 

I am trying to get the \<Sign\> content from the data, for example:
```xml
<ProductFeature Localized="0" ID="242315270" Local_ID="0" Value="4" CategoryFeature_ID="73753" CategoryFeatureGroup_ID="106" No="10100050" Presentation_Value="4 GB" Translated="0" Mandatory="1" Searchable="1">
  <LocalValue Value="4">
    <Measure ID="20">
      <Signs>
        <Sign ID="7" langid="1">
          <![CDATA[GB]]>
        </Sign>
      </Signs>
    </Measure>
  </LocalValue>
  ...
</ProductFeature> 
```

When I access it in myResult.php like the following:
```php
foreach ($this->getProductData()->ProductFeature as $feature) {
    ...
    $sign = $feature->LocalValue->Measure->Signs->Sign;
    ...
}
```

A error will throw:
```php
PHP Catchable fatal error:  Object of class stdClass could not be converted to string
```

And by dumping the content in the Sign, it is like this:
```php
class stdClass#1555 (1) {
  public $@attributes =>
  class stdClass#1554 (2) {
    public $ID =>
    string(2) "20"
    public $langid =>
    string(1) "1"
  }
}
```

Problem sloved by adding the LIBXML_NOCDATA.
Hope these information can help.
Not sure if I have time to write tests, but I will write the test if I do.

Regards,
Pete

**Comment by haringsrob** [comment]
Hi Pete,

I added the tests, should be green when merging this, however, it will implement new functionality and will break backward compatibility.

Can you have a look? #6

**Comment by chanpete** [comment]
Hi Rob

I saw the change, it is good.
If you want to keep the backward compatibility, I think you can do something like this:
```php
public function getSpecByName($specificationName, $parseSpec = false)
{
    foreach (...) {
        if (...) {
            return $parseSpec ? new Specification($feature) : $feature->{'@attributes'}->Presentation_Value;
        }
    }
    if (!$parseSpec) {
        return null;
    }
    throw new SpecificationNotFoundException(
        ...
    );
}
```
Although it is ugly...

**Comment by haringsrob** [comment]
Yea. I am ok with breaking compatibility. I will tag it with a proper version indicating these changes.

**Comment by chanpete** [comment]
Good, can't wait for the update! :)

**Comment by haringsrob** [comment]
Chanpete can you recreate the pull request against master? Then this can also be merged there.

**Comment by haringsrob** [comment]
Done in #6 version 2.0.0 is already having the updated code.

**Comment by chanpete** [comment]
So, should I recreate the pull request?

**Comment by haringsrob** [comment]
No it is ok. I created it.

**Comment by chanpete** [comment]
OK, thank you 👍

**Pull request merged**
